//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamifyDesktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class e_exam
    {
        public int e_id { get; set; }
        public string e_title { get; set; }
        public Nullable<byte> e_complete { get; set; }
        public string e_subject { get; set; }
        public Nullable<int> e_s_id { get; set; }
        public string e_type { get; set; }
        public Nullable<System.DateTime> e_date { get; set; }
    
        public virtual s_student s_student { get; set; }
    }
}
