//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamifyDesktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class s_student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public s_student()
        {
            this.e_exam = new HashSet<e_exam>();
        }
    
        public int s_id { get; set; }
        public string s_first_name { get; set; }
        public string s_last_name { get; set; }
    
        public virtual s_student s_student1 { get; set; }
        public virtual s_student s_student2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<e_exam> e_exam { get; set; }
    }
}
